### ISSUE TITLE
errno: -36, code: 'ENAMETOOLONG'

### ISSUE THREAD

**Issue by kkkumar-1** [iamtheyammer/fetch-ford-service-manuals#11]
Dear all,

Am trying to pull Ford Fiesta workshop manuals and am seeing error related to 'file name too long'

Can someone please help me with the issue?
Please see the error screenshot.

![Uploading Screenshot 2024-02-09 160050.png…]()

Thanks in advance

**Comment by iamtheyammer** [comment]
@kkkumar-1 sent me a working screenshot via email:

![image](https://github.com/iamtheyammer/fetch-ford-service-manuals/assets/32084206/cd98d737-41f4-4090-a7b4-8271dc3e3e8d)

On Ubuntu, the maximum path length is 256 characters, and, here, the attempted path is:

```
/2015-fiesta-test/2: Chassis/04: Suspension/204-02 Rear Suspension/Removal and Installation/Wheel Hub - 1.0L Duratec (48kW-65PS)-1.0L Duratec (59kW-80PS)-1.0L EcoBoost (74kW-100PS)-1.0L EcoBoost (90kW-120PS)-1.25L Duratec-16V (44kW-60PS) - Sigma-1.25L Duratec-16V (60kW-82PS) - Sigma-1.3L Z6 (83PS) - BZ-1.4L Duratec-16V (70kW-95PS) - Sigma-1.4L Duratec-16V (71kW-96PS) - Sigma-1.4L Duratec-16V Flex Fuel (71kW-96PS) - Sigma-1.4L Duratorq-TDCi (51kW-68PS)-1.5L Duratec-16V Flex Fuel (77kW-105PS)-1.5L Duratec-16V Ti-VCT (81kW-110PS) - Sigma-1.5L Duratorq-TDCi (55kW-75PS)-1.5L Duratorq-TDCi (67kW-91PS)-1.5L Z6 (101PS) - BZ-1.6L Duratec-16V Ti-VCT (77kW-105PS) - Sigma-1.6L Duratec-16V Ti-VCT (88kW-120PS) - Sigma-1.6L Duratec-16V Ti-VCT (99kW-134PS) - Sigma-1.6L Duratec-16V Ti-VCT Flex Fuel (92kW-125PS) - Sigma-1.6L Duratorq-TDCi (55kW-75PS)-1.6L Duratorq-TDCi (66kW-90PS)-1.6L Duratorq-TDCi (70kW-95PS) (T3)-1.6L Duratorq-TDCi (70kW-95PS) (TZ).html
```

Where the final file path is a whopping 850 characters (wow!). I'll have to add a check to truncate these insane filenames.

**Comment by iamtheyammer** [comment]
Should be fixed, so I'm closing this issue. Comment here to re-open it if it doesn't work.

**Comment by kkkumar-1** [comment]
Hey Sam,

I checked the code on a completely new VM setup and unfortunately, the error remains the same.
Kindly check the attached error screenshot


![image](https://github.com/iamtheyammer/fetch-ford-service-manuals/assets/143082770/c5b71adc-0e0a-42db-a511-6abf444f9eee)

**Comment by iamtheyammer** [comment]
Shoot. Can you copy paste the error here?

**Comment by kkkumar-1** [comment]
Downloading manual page Rear Suspension - Overview.html (docID: G1526781)
Downloading manual page Rear Suspension.html (docID: G1604445)
Downloading manual page Wheel Hub - 1.0L Duratec (48kW/65PS)/1.0L Duratec (59kW/80PS)/1.0L EcoBoost (74kW/100PS)/1.0L EcoBoost (90kW/120PS)/1.25L Duratec-16V (44kW/60PS) – Sigma/1.25L Duratec-16V (60kW/82PS) – Sigma/1.3L Z6 (83PS) – BZ/1.4L Duratec-16V (70kW/95PS) – Sigma/1.4L Duratec-16V (71kW/96PS) – Sigma/1.4L Duratec-16V Flex Fuel (71kW/96PS) – Sigma/1.4L Duratorq-TDCi (51kW/68PS)/1.5L Duratec-16V Flex Fuel (77kW/105PS)/1.5L Duratec-16V Ti-VCT (81kW/110PS) – Sigma/1.5L Duratorq-TDCi (55kW/75PS)/1.5L Duratorq-TDCi (67kW/91PS)/1.5L Z6 (101PS) – BZ/1.6L Duratec-16V Ti-VCT (77kW/105PS) – Sigma/1.6L Duratec-16V Ti-VCT (88kW/120PS) – Sigma/1.6L Duratec-16V Ti-VCT (99kW/134PS) – Sigma/1.6L Duratec-16V Ti-VCT Flex Fuel (92kW/125PS) – Sigma/1.6L Duratorq-TDCi (55kW/75PS)/1.6L Duratorq-TDCi (66kW/90PS)/1.6L Duratorq-TDCi (70kW/95PS) (T3)/1.6L Duratorq-TDCi (70kW/95PS) (TZ).html (docID: G1526788)
-> Truncating filename, learn more in the README
[Error: ENAMETOOLONG: name too long, open '/home/2015-Fiesta-attemp-1/2: Chassis/04: Suspension/204-02 Rear Suspension/Removal and Installation/Wheel Hub - 1.0L Duratec (48kW-65PS)-1.0L Duratec (59kW-80PS)-1.0L EcoBoost (74kW-100PS)-1.0L EcoBoost (90kW-120PS)-1.25L Duratec-16V (44kW-60PS) – Sigma-1.25L Duratec-16V (60kW-82PS) – Sigma-1.3L Z6 (83PS) – BZ-1.4L Duratec-16V (70kW (G1526788 truncated).html'] {
  errno: -36,
  code: 'ENAMETOOLONG',
  syscall: 'open',
  path: '/home/2015-Fiesta-attemp-1/2: Chassis/04: Suspension/204-02 Rear Suspension/Removal and Installation/Wheel Hub - 1.0L Duratec (48kW-65PS)-1.0L Duratec (59kW-80PS)-1.0L EcoBoost (74kW-100PS)-1.0L EcoBoost (90kW-120PS)-1.25L Duratec-16V (44kW-60PS) – Sigma-1.25L Duratec-16V (60kW-82PS) – Sigma-1.3L Z6 (83PS) – BZ-1.4L Duratec-16V (70kW (G1526788 truncated).html'
}

**Comment by iamtheyammer** [comment]
Looks like the path is 260 once you add the file extension:

```
Wheel Hub - 1.0L Duratec (48kW-65PS)-1.0L Duratec (59kW-80PS)-1.0L EcoBoost (74kW-100PS)-1.0L EcoBoost (90kW-120PS)-1.25L Duratec-16V (44kW-60PS) – Sigma-1.25L Duratec-16V (60kW-82PS) – Sigma-1.3L Z6 (83PS) – BZ-1.4L Duratec-16V (70kW (G1526788 truncated).html
```

Just need to adjust the offsets.

**Comment by iamtheyammer** [comment]
File names are limited to 255 bytes, not 255 characters. Ford cleverly uses an emdash (–), a three-byte Unicode character, instead of the normal one-byte -. Added this to the illegal characters regex.

**Comment by kkkumar-1** [comment]
Sam, you are a genius :-)

You have fixed it.

I really thank you once again for your time & efforts.  Appreciate it.

**Comment by iamtheyammer** [comment]
Glad to hear it :)

Enjoy the manual!
